# Generated by Django 5.2.4 on 2025-07-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="book",
            name="published_date",
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.CharField(default="Unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.CharField(max_length=20),
        ),
    ]
