# Generated by Django 5.2.4 on 2025-07-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_author_remove_book_isbn_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table="books",
        ),
    ]
