# Generated by Django 5.2.4 on 2025-07-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
